Repository auto-mat/ride-to-work-by-bike-frontend, pull requests merged in 2023-10, with the labels that each got.

#10 src/components/__tests__: fix BadgeAchievement, CardFollow, CardOffer, NewsletterFeature component tests
  .gitignore
  quasar.config.js
  src/components/BadgeAchievement.vue
  src/components/CardFollow.vue
  src/components/NewsletterFeature.vue
  src/components/__tests__/BadgeAchievement.cy.js
  src/components/__tests__/CardFollow.cy.js
  src/components/__tests__/CardOffer.cy.js
  src/mocks/homepage.ts
  test/cypress/support/commands.js
  test/cypress/support/component.js
Labels: bug, component tests, MS Windows

#11 Update README doc
  README.md
Labels: documentation

#12 .github/workflows: add delete old workflows GitHub actions workflow
  .github/workflows/delete_old_workflows.yaml
Labels: CI

#13 src/components: add deployed frontend app version info
  src/components/TheFooter.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: enhancement

#15 Enable CI Renovate bot instead of Dependency bot
  renovate.json
Labels: enhancement, CI

#19 src/components: fix showing deployed frontend app version info into mobile viewport
  src/components/TheFooter.vue
Labels: bug, mobile viewport

#14 test/cypress/e2e: fix ResizeObserver loop completed with undelivered notifications error
  src/components/TheFooter.vue
  test/cypress/e2e/home.spec.cy.js
  test/cypress/support/commands.js
Labels: bug, e2e tests

#44 src/components: rename component file name/name plus fix icon alignment
  src/components/FooterBar.vue
  src/components/__tests__/FooterBar.cy.js
  src/layouts/MainLayout.vue
Labels: enhancement

#49 src/components/__tests__: comment unused const var
  src/components/__tests__/CardEvent.cy.js
Labels: bug, component tests

#48 src/components: add component docs, cleanup props and format
  src/components/BadgeAchievement.vue
  src/components/BannerApp.vue
  src/components/BannerImage.vue
  src/components/BannerRoutes.vue
  src/components/CardChallenge.vue
  src/components/CardEvent.vue
  src/components/CardFollow.vue
  src/components/CardOffer.vue
  src/components/CardPost.vue
  src/components/CardProgress.vue
  src/components/CardProgressSlider.vue
  src/components/CardStats.vue
  src/components/ContactForm.vue
  src/components/DialogCard.vue
  src/components/DialogStates.vue
  src/components/DrawerHeader.vue
  src/components/DrawerMenu.vue
  src/components/EventCountdown.vue
  src/components/FooterBar.vue
  src/components/HeadingBackground.vue
  src/components/LanguageSwitcher.vue
  src/components/ListBadgeAchievement.vue
  src/components/ListCardChallenge.vue
  src/components/ListCardEvent.vue
  src/components/ListCardFollow.vue
  src/components/ListCardOffer.vue
  src/components/ListCardPost.vue
  src/components/ListCardProgress.vue
  src/components/ListFaq.vue
  src/components/MenuLinks.vue
  src/components/MobileBottomPanel.vue
  src/components/NewsletterFeature.vue
  src/components/NewsletterItem.vue
  src/components/SliderProgress.vue
  src/components/UserSelect.vue
  src/components/__tests__/CardOffer.cy.js
  src/components/__tests__/NewsletterFeature.cy.js
  test/cypress/e2e/home.spec.cy.js
  test/cypress/support/commands.js
Labels: documentation, enhancement

#53 src/components/__tests__: split command chaining to fix eslint cypress plugin error
  src/components/__tests__/CardEvent.cy.js
  src/components/__tests__/CardOffer.cy.js
  src/components/__tests__/DrawerHeader.cy.js
  src/components/__tests__/ListFaq.cy.js
  src/components/__tests__/UserSelect.cy.js
Labels: bug, component tests

#55 test/cypress/e2e: fix Cypress e2e tests unsafe to chain command error message
  test/cypress/e2e/home.spec.cy.js
Labels: bug

#57 ts: fix run Cypress e2e unit tests with TypeScript version 5.0.0
  tsconfig.json
Labels: bug, e2e tests

#51 src/layouts/login: add login route + updated page header
  renovate.json
  ride_to_work_by_bike_config.toml
  src/assets/svg/logo.svg
  src/components/DrawerHeader.vue
  src/components/FooterBar.vue
  src/components/HelpButton.vue
  src/components/LanguageSwitcher.vue
  src/components/ListFaq.vue
  src/components/__tests__/DrawerHeader.cy.js
  src/components/__tests__/FooterBar.cy.js
  src/components/__tests__/HelpButton.cy.js
  src/components/__tests__/LanguageSwitcher.cy.js
  src/components/types/Config.ts
  src/css/utility.scss
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/layouts/LoginLayout.vue
  src/layouts/MainLayout.vue
  src/pages/LoginPage.vue
  src/router/routes.ts
  src/utils/get_app_conf.js
  test/cypress/e2e/home.spec.cy.js
  test/cypress/e2e/login.spec.cy.js
Labels: enhancement

#63 src/pages: add login page title
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/LoginPage.vue
  test/cypress/e2e/login.spec.cy.js
Labels: enhancement

#65 Improving way ho to run Cypress component/e2e tests
  .github/workflows/run_tests.yaml
  README.md
  package.json
  test/cypress/run_tests.sh
Labels: documentation, enhancement, component tests, e2e tests, CI

#67 tests/cypress: fix default Cypress tests web browsers value
  .github/workflows/run_tests.yaml
  README.md
  package.json
  test/cypress/run_tests.sh
Labels: bug, component tests, e2e tests, MS Windows, CI

#60 src/components: add BannerRoutes component variant property
  src/components/BannerRoutes.vue
  src/components/__tests__/BannerRoutes.cy.js
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/IndexPage.vue
Labels: enhancement

#58 src/components: add SectionColumns component
  src/components/SectionColumns.vue
  src/components/SectionColumnsTest.vue
  src/components/__tests__/SectionColumns.cy.js
  src/mocks/homepage.ts
  src/pages/IndexPage.vue
Labels: enhancement

#66 src/components: add CountdownChallenge component
  src/components/CountdownChallenge.vue
  src/components/__tests__/CountdownChallenge.cy.js
  src/composables/useCountdown.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/IndexPage.vue
Labels: enhancement

#71 src/components: use relative module import
  src/components/BannerApp.vue
  src/components/BannerImage.vue
  src/components/CardChallenge.vue
  src/components/CardEvent.vue
  src/components/CardFollow.vue
  src/components/CardOffer.vue
  src/components/CardPost.vue
  src/components/CardProgress.vue
  src/components/CardProgressSlider.vue
  src/components/CountdownChallenge.vue
  src/components/DrawerMenu.vue
  src/components/EventCountdown.vue
  src/components/FooterBar.vue
  src/components/HelpButton.vue
  src/components/LanguageSwitcher.vue
  src/components/ListCardChallenge.vue
  src/components/ListCardEvent.vue
  src/components/ListCardFollow.vue
  src/components/ListCardOffer.vue
  src/components/ListFaq.vue
  src/components/MenuLinks.vue
  src/components/MobileBottomPanel.vue
  src/components/NewsletterFeature.vue
  src/components/NewsletterItem.vue
  src/components/SectionColumnsTest.vue
  src/components/UserSelect.vue
  src/components/__tests__/BadgeAchievement.cy.js
  src/components/__tests__/BannerApp.cy.js
  src/components/__tests__/BannerImage.cy.js
  src/components/__tests__/BannerRoutes.cy.js
  src/components/__tests__/CardChallenge.cy.js
  src/components/__tests__/CardEvent.cy.js
  src/components/__tests__/CardFollow.cy.js
  src/components/__tests__/CardOffer.cy.js
  src/components/__tests__/CardPost.cy.js
  src/components/__tests__/CardProgress.cy.js
  src/components/__tests__/CardProgressSlider.cy.js
  src/components/__tests__/CardStats.cy.js
  src/components/__tests__/CountdownChallenge.cy.js
  src/components/__tests__/FooterBar.cy.js
  src/components/__tests__/HeadingBackground.cy.js
  src/components/__tests__/HelpButton.cy.js
  src/components/__tests__/LanguageSwitcher.cy.js
  src/components/__tests__/ListBadgeAchievement.cy.js
  src/components/__tests__/ListCardEvent.cy.js
  src/components/__tests__/ListCardFollow.cy.js
  src/components/__tests__/ListCardOffer.cy.js
  src/components/__tests__/ListCardPost.cy.js
  src/components/__tests__/ListCardProgress.cy.js
  src/components/__tests__/ListFaq.cy.js
  src/components/__tests__/MenuLinks.cy.js
  src/components/__tests__/NewsletterFeature.cy.js
  src/components/__tests__/NewsletterItem.cy.js
  src/components/__tests__/SectionColumns.cy.js
  src/components/__tests__/SliderProgress.cy.js
  src/components/__tests__/UserSelect.cy.js
Labels: JS

#72 src: harmonize import JS/TS modules using absolute path alias import
  src/layouts/LoginLayout.vue
  src/layouts/MainLayout.vue
  src/pages/IndexPage.vue
  src/pages/LoginPage.vue
Labels: JS

#77 Upgrade Node.js version to the last LTS Iron 20.x version
  .github/workflows/run_tests.yaml
  README.md
Labels: enhancement, CI

#78 docker: upgrade Node.js version to the last LTS Iron 20.x version
  docker/Dockerfile
  docker/dev/Dockerfile
Labels: enhancement, JS, docker

#81 Install and use pre-commit hook JS lib husky, lint-staged
  .husky/pre-commit
  .lintstagedrc
  doc/dev/pre_commit.md
  package.json
  yarn.lock
Labels: documentation, enhancement, dev tools

#74 src/components: add FormLogin component with component/e2e tests
  src/components/FormLogin.vue
  src/components/__tests__/FormLogin.cy.js
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/LoginPage.vue
  test/cypress/e2e/login.spec.cy.js
Labels: enhancement

#84 test/cypress: fix Cy component/e2e tests execution if the -s flag is used
  test/cypress/run_tests.sh
Labels: bug, component tests, e2e tests

#87 Fix run Cypress test framework from dev Dockerfile
  README.md
  docker/dev/Dockerfile
  docker/dev/install_app_dependencies.sh
  docker/dev/install_custom_packages.sh
Labels: documentation, component tests, e2e tests, docker

#88 .github/workflows: automatically build and push dev Dockerfile Docker image
  .github/workflows/build_dev_dockefile_docker_image.yaml
Labels: docker

#89 Move cypress-image-snapshot JS lib into dev dependencies section
  package.json
  yarn.lock
Labels: JS lib

#90 docker: fix installing only app dependencies in production Docker image
  docker/Dockerfile
Labels: docker

#93 src/components: implement login forgotten password
  quasar.config.js
  src/components/FormLogin.vue
  src/components/__tests__/FormLogin.cy.js
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/LoginPage.vue
  test/cypress/e2e/home.spec.cy.js
  test/cypress/e2e/login.spec.cy.js
  test/cypress/plugins/index.js
Labels: enhancement

#94 src/components: rename EventCountdown component to CountdownEvent
  src/components/CountdownChallenge.vue
  src/components/CountdownEvent.vue
  src/components/__tests__/CountdownEvent.js
  src/mocks/homepage.ts
  src/pages/IndexPage.vue
  test/cypress/e2e/home.spec.cy.js
  test/cypress/e2e/login.spec.cy.js
Labels: enhancement

#97 Format repo with yarn format
  index.html
  src/components/BannerApp.vue
  src/components/BannerImage.vue
  src/components/BannerRoutes.vue
  src/components/CardChallenge.vue
  src/components/CardEvent.vue
  src/components/CardFollow.vue
  src/components/CardOffer.vue
  src/components/CardPost.vue
  src/components/CardProgress.vue
  src/components/CardProgressSlider.vue
  src/components/CardStats.vue
  src/components/FooterBar.vue
  src/components/HelpButton.vue
  src/components/LanguageSwitcher.vue
  src/components/RideToWorkByBike.vue
  src/components/SectionColumnsTest.vue
  src/components/__tests__/ContactForm.cy.js
  src/components/__tests__/DrawerMenu.cy.js
  src/components/types/Card.ts
  src/layouts/MainLayout.vue
  src/utils/get_app_conf.js
  test/cypress/support/commands.js
  test/cypress/support/component-index.html
Labels: enhancement

#99 src/boot: declare global color config vars
  quasar.config.js
  ride_to_work_by_bike_config.toml
  src/boot/global_vars.js
  src/components/BannerImage.vue
  src/components/CountdownChallenge.vue
  src/components/CountdownEvent.vue
  src/components/FormLogin.vue
  src/components/HelpButton.vue
  src/components/LanguageSwitcher.vue
  src/components/types/Config.ts
  src/layouts/MainLayout.vue
  src/pages/LoginPage.vue
  src/utils/get_app_conf.js
  test/cypress/support/component.js
Labels: enhancement

#103 src/components: add BannerAppButtons component with component test
  ride_to_work_by_bike_config.toml
  src/assets/svg/appstore.svg
  src/assets/svg/googleplay.svg
  src/components/BannerAppButtons.vue
  src/components/FormLogin.vue
  src/components/__tests__/BannerAppButtons.cy.js
  src/components/types/Config.ts
  src/css/utility.scss
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/utils/get_app_conf.js
Labels: enhancement
