Repository auto-mat/ride-to-work-by-bike-frontend, pull requests merged in 2024-09, with the labels that each got.

#530 src/components/profile: add new rows to section ProfileDetails
  src/components/__tests__/AddressDisplay.cy.js
  src/components/__tests__/ProfileDetails.cy.js
  src/components/global/AddressDisplay.vue
  src/components/profile/ProfileDetails.vue
  src/components/types/Profile.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  test/cypress/fixtures/formAddress.json
  test/cypress/fixtures/formPersonalDetails.json
Labels: enhancement

#540 src/components/form: make Gender field in FormPersonalDetails required
  src/components/__tests__/FormPersonalDetails.cy.js
  src/components/form/FormFieldRadioRequired.vue
  src/components/form/FormPersonalDetails.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  test/cypress/e2e/register_challenge.spec.cy.js
Labels: enhancement

#529 src/components/register: add component RegisterChallengePayment for configuring payment
  quasar.config.js
  ride_to_work_by_bike_config.toml
  src/components/__tests__/FormFieldCheckboxRequired.cy.js
  src/components/__tests__/FormFieldCheckboxTeam.cy.js
  src/components/__tests__/FormFieldDonation.cy.js
  src/components/__tests__/FormFieldPassword.cy.js
  src/components/__tests__/FormFieldSliderNumber.cy.js
  src/components/__tests__/FormFieldVoucher.cy.js
  src/components/__tests__/RegisterChallengePayment.cy.js
  src/components/__tests__/RouteInputTransportType.cy.js
  src/components/form/FormFieldDonation.vue
  src/components/form/FormFieldRadioRequired.vue
  src/components/form/FormFieldSliderNumber.vue
  src/components/form/FormFieldVoucher.vue
  src/components/global/FormFieldCompany.vue
  src/components/global/FormFieldPhone.vue
  src/components/global/FormFieldTestWrapper.vue
  src/components/global/FormFieldTextRequired.vue
  src/components/register/RegisterChallengePayment.vue
  src/components/types/Config.ts
  src/components/types/Form.ts
  src/composables/useFormatPrice.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/RegisterChallengePage.vue
  src/utils/get_app_conf.js
  test/cypress/fixtures/registerPaymentVoucherFull.json
  test/cypress/fixtures/registerPaymentVoucherHalf.json
  test/cypress/support/commands.js
  test/cypress/support/component.js
Labels: enhancement

#531 config: change default font from Roboto to Poppins
  quasar.config.js
  src/assets/font/poppins/poppins-v21-latin_latin-ext-500.woff2
  src/assets/font/poppins/poppins-v21-latin_latin-ext-500italic.woff2
  src/assets/font/poppins/poppins-v21-latin_latin-ext-700.woff2
  src/assets/font/poppins/poppins-v21-latin_latin-ext-700italic.woff2
  src/assets/font/poppins/poppins-v21-latin_latin-ext-italic.woff2
  src/assets/font/poppins/poppins-v21-latin_latin-ext-regular.woff2
  src/css/app.scss
  src/css/fonts.scss
  src/css/quasar.variables.scss
  test/cypress/e2e/home.spec.cy.js
Labels: enhancement

#543 src/components/homepage: update CardEvent styling based on graphic design
  public/icons/card_event/icons.svg
  src/components/__tests__/CardEvent.cy.js
  src/components/global/ButtonAddToCalendar.vue
  src/components/homepage/CardEvent.vue
Labels: enhancement

#542 src/stores: add registerChallenge store and connect personalDetails and company sections
  src/components/__tests__/FormFieldCompanyAddress.cy.js
  src/components/__tests__/FormFieldSelectTable.cy.js
  src/components/__tests__/FormLogin.cy.js
  src/components/__tests__/FormSelectOrganization.cy.js
  src/components/__tests__/HeaderOrganization.cy.js
  src/components/coordinator/HeaderOrganization.vue
  src/components/form/FormFieldCompanyAddress.vue
  src/components/form/FormFieldRadioRequired.vue
  src/components/form/FormFieldSelectTable.vue
  src/components/form/FormPersonalDetails.vue
  src/components/form/FormSelectOrganization.vue
  src/components/login/FormLogin.vue
  src/components/types/Form.ts
  src/components/types/Organization.ts
  src/components/types/Profile.ts
  src/composables/useSelectedOrganization.ts
  src/i18n/en.toml
  src/pages/RegisterChallengePage.vue
  src/stores/login.ts
  src/stores/registerChallenge.ts
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/formCreateInvoice.json
  test/cypress/fixtures/formOrganizationOptions.json
  test/cypress/fixtures/headerOrganization.json
Labels: enhancement

#557 src/boot: register Pinia Vue store JS lib
  quasar.config.js
  src/boot/pinia.js
Labels: bug

#552 src/components/homepage: update NewsletterFeature styling based on graphic design
  src/assets/image/newsletter-feature/newsletter.webp
  src/components/__tests__/NewsletterFeature.cy.js
  src/components/homepage/NewsletterFeature.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: enhancement

#558 src/components: update component ListCardFollow based on graphic design
  public/icons/lucide.svg
  src/components/__tests__/CardFollow.cy.js
  src/components/__tests__/ListCardFollow.cy.js
  src/components/homepage/CardFollow.vue
  src/components/homepage/ListCardFollow.vue
Labels: enhancement

#554 src/components: add section registration details to ProfileDetails component
  src/components/__tests__/ProfileDetails.cy.js
  src/components/profile/ProfileDetails.vue
  src/components/types/Profile.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  test/cypress/fixtures/formPersonalDetails.json
Labels: enhancement

#527 src/components/homepage: update styling of BannerRoutes component based on design
  src/assets/svg/banner-routes.svg
  src/components/__tests__/BannerRoutes.cy.js
  src/components/homepage/BannerRoutes.vue
  test/cypress/support/commands.js
Labels: enhancement

#547 src/components: add component ProfileCoordinatorContact to display a notice in ProfileDetails
  public/icons/profile_coordinator_contact/icons.svg
  src/assets/svg/profile-placeholder.svg
  src/components/__tests__/ProfileCoordinatorContact.cy.js
  src/components/__tests__/ProfileDetails.cy.js
  src/components/profile/ProfileCoordinatorContact.vue
  src/components/profile/ProfileDetails.vue
  src/components/types/Profile.ts
  src/css/utility.scss
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  test/cypress/fixtures/companyCoordinator.json
Labels: enhancement

#561 src/components/__tests__: correct time setting in TaskListCoordinator tests
  src/components/__tests__/TaskListCoordinator.cy.js
Labels: bug, component tests

#560 src/components: Update styling for HelpButton component
  public/icons/button_icons.svg
  src/components/__tests__/ContactForm.cy.js
  src/components/__tests__/DrawerHeader.cy.js
  src/components/__tests__/HelpButton.cy.js
  src/components/__tests__/LoginRegisterHeader.cy.js
  src/components/global/ContactForm.vue
  src/components/global/DrawerHeader.vue
  src/components/global/HelpButton.vue
  src/components/global/LoginRegisterHeader.vue
Labels: enhancement

#565 src/components/global: update component FooterBar based on graphic design
  ride_to_work_by_bike_config.toml
  src/assets/svg/logo-automat.svg
  src/components/__tests__/FooterBar.cy.js
  src/components/global/FooterBar.vue
  src/components/types/Config.ts
  src/css/utility.scss
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/layouts/MainLayout.vue
  src/utils/get_app_conf.js
Labels: enhancement

#571 src/components/profile: add a toggle setting in ProfileDetails component
  src/components/__tests__/ProfileDetails.cy.js
  src/components/profile/ProfileDetails.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: enhancement

#551 src/components: add component TableNotifications for displaying user notifications
  src/components/__tests__/TableNotifications.cy.js
  src/components/profile/ProfileTabs.vue
  src/components/profile/TableNotifications.vue
  src/components/types/Notifications.ts
  src/components/types/Table.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  test/cypress/fixtures/tableNotifications.json
Labels: enhancement

#577 src/utils: replace JS fs package with fs-extra package
  package.json
  src/utils/get_app_conf.js
  src/utils/get_deployed_app_version.js
  yarn.lock
Labels: bug

#572 test/cypress/e2e: add E2E tests for the Profile page and fix bugs
  src/components/__tests__/ProfileDetails.cy.js
  src/components/form/FormUpdateGender.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/ProfilePage.vue
  test/cypress/e2e/profile.spec.cy.js
Labels: bug, enhancement

#579 src/components/__tests__: fix FormFieldCompany component correct layout
  src/components/__tests__/FormFieldCompany.cy.js
  src/components/global/FormFieldCompany.vue
Labels: bug

#581 src/components/form: fix build process minification issue with correct lang attribute
  src/components/form/FormPersonalDetails.vue
Labels: bug

#576 src/components: update component DrawerMenu styling based on graphic design
  public/icons/drawer_menu/icons.svg
  src/components/__tests__/DrawerMenu.cy.js
  src/components/global/DrawerHeader.vue
  src/components/global/DrawerMenu.vue
  src/css/quasar.variables.scss
  src/layouts/MainLayout.vue
  src/mocks/layout.ts
  test/cypress/e2e/community.spec.cy.js
  test/cypress/e2e/company_coordinator.spec.cy.js
  test/cypress/e2e/home.spec.cy.js
  test/cypress/e2e/prizes.spec.cy.js
  test/cypress/e2e/results.spec.cy.js
  test/cypress/e2e/results_detail.spec.cy.js
  test/cypress/e2e/routes.spec.cy.js
Labels: enhancement

#583 test/cypress/e2e: fix profile e2e test by testing new menu selectors
  test/cypress/e2e/profile.spec.cy.js
Labels: bug

#559 src/boot: add axios library and implement post composable for login action
  package.json
  ride_to_work_by_bike_config.toml
  src/boot/axios.js
  src/boot/pinia.js
  src/components/__tests__/FormLogin.cy.js
  src/components/login/FormLogin.vue
  src/components/types/Config.ts
  src/components/types/Logger.ts
  src/composables/useApi.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/stores/login.ts
  src/utils/get_app_conf.js
  test/cypress/support/commonTests.ts
  yarn.lock
Labels: enhancement

#587 test/cypress/support: fix command for testing translation strings
  test/cypress/support/commands.js
Labels: bug

#591 Fix REST API login URL missing / on the end of URL path
  ride_to_work_by_bike_config.toml
Labels: bug

#582 src/layouts: add image background to the LoginRegister layout
  public/image/login-register-layout.webp
  ride_to_work_by_bike_config.toml
  src/components/global/LoginRegisterHeader.vue
  src/components/types/Config.ts
  src/layouts/LoginRegisterLayout.vue
  src/pages/LoginPage.vue
  src/pages/RegisterChallengePage.vue
  src/pages/RegisterCoordinatorPage.vue
  src/pages/RegisterPage.vue
  src/utils/get_app_conf.js
  test/cypress/e2e/login.spec.cy.js
  test/cypress/e2e/register.spec.cy.js
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/e2e/register_coordinator.spec.cy.js
  test/cypress/support/commonTests.ts
Labels: enhancement

#564 src/components/global: add component ButtonNotifications for displaying new notifications
  public/icons/button_notifications/icons.svg
  src/components/__tests__/ButtonNotifications.cy.js
  src/components/__tests__/DrawerHeader.cy.js
  src/components/__tests__/ForumPostItem.cy.js
  src/components/__tests__/TableNotifications.cy.js
  src/components/global/ButtonNotifications.vue
  src/components/global/DrawerHeader.vue
  src/components/profile/TableNotifications.vue
  src/composables/useFormatDate.ts
  src/composables/useNotifications.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  test/cypress/e2e/profile.spec.cy.js
  test/cypress/fixtures/notifications.json
Labels: enhancement

#586 src/components/global: update styling for UserSelect component + tests
  public/icons/user_select/icons.svg
  src/components/__tests__/UserSelect.cy.js
  src/components/global/DrawerHeader.vue
  src/components/global/UserSelect.vue
  src/components/types/Link.ts
  src/components/types/User.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/layouts/MainLayout.vue
  src/mocks/layout.ts
  test/cypress/e2e/community.spec.cy.js
  test/cypress/e2e/company_coordinator.spec.cy.js
  test/cypress/e2e/home.spec.cy.js
  test/cypress/e2e/prizes.spec.cy.js
  test/cypress/e2e/profile.spec.cy.js
  test/cypress/e2e/results.spec.cy.js
  test/cypress/e2e/results_detail.spec.cy.js
  test/cypress/e2e/routes.spec.cy.js
  test/cypress/e2e/routes_calendar.cy.js
  test/cypress/support/commonTests.ts
Labels: enhancement

#588 src/components/homepage: update styling for the CardProgress component
  public/icons/card_progress/icons.svg
  src/components/__tests__/CardProgress.cy.js
  src/components/__tests__/CardProgressSlider.cy.js
  src/components/homepage/CardProgress.vue
  src/composables/useCircleSize.ts
  src/css/circular-progress.scss
Labels: enhancement

#593 src/components: update styling for NewsletterItem component
  public/icons/newsletter_item/icons.svg
  ride_to_work_by_bike_config.toml
  src/components/__tests__/NewsletterItem.cy.js
  src/components/homepage/NewsletterFeature.vue
  src/components/homepage/NewsletterItem.vue
  src/components/types/Config.ts
  src/mocks/homepage.ts
  src/utils/get_app_conf.js
  test/cypress/support/commonTests.ts
Labels: enhancement
