Repository auto-mat/ride-to-work-by-bike-frontend, pull requests merged in 2024-05, with the labels that each got.

#365 src/components/__tests__: add blur event to phone input validation tests to prevent test failure
  src/components/__tests__/FormFieldPhone.cy.js
Labels: bug, component tests

#357 src/components/routes: add RouteLockedContent component
  ride_to_work_by_bike_config.toml
  src/components/__tests__/RouteLockedContent.cy.js
  src/components/routes/RouteLockedContent.vue
  src/components/types/Config.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/utils/get_app_conf.js
Labels: enhancement

#353 src/pages/RoutesPage: add Tabs component with navigation history to /routes page
  src/components/__tests__/RouteTabs.cy.js
  src/components/routes/RouteTabs.vue
  src/components/types/Route.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/RoutesPage.vue
  src/router/routes.ts
  src/router/routes_conf.ts
  test/cypress/e2e/routes.spec.cy.js
Labels: enhancement

#380 Run Cypress tests parallel
  .github/workflows/run_tests.yaml
  README.md
  package.json
  test/cypress/e2e/.keep
  yarn.lock
Labels: enhancement, component tests, e2e tests, CI

#363 src/components/routes/RouteApp: add component to render content of the App tab in /routes
  src/components/__tests__/BannerRoutesApp.cy.js
  src/components/__tests__/RoutesApps.cy.js
  src/components/routes/BannerRoutesApp.vue
  src/components/routes/RoutesApps.vue
  src/components/types/Banner.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  test/cypress/fixtures/bannerRoutesAppList.json
Labels: enhancement

#376 src/components/__tests__: simplify ListCardPost tests by removing cy.window wrapper
  src/components/__tests__/ListCardPost.cy.js
Labels: enhancement

#375 test/cypress/e2e: remove duplicated tests for better performance
  src/components/__tests__/LoginRegisterHeader.cy.js
  test/cypress/e2e/home.spec.cy.js
  test/cypress/e2e/login.spec.cy.js
Labels: bug

#379 src/components/routes: add component `RoutesBottomPanel` for logging route data
  src/components/__tests__/RouteItemEdit.cy.js
  src/components/__tests__/RouteListEdit.cy.js
  src/components/__tests__/RoutesBottomPanel.cy.js
  src/components/routes/RouteItemEdit.vue
  src/components/routes/RouteListEdit.vue
  src/components/routes/RoutesBottomPanel.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  test/cypress/fixtures/routeList.json
  test/cypress/fixtures/routeListItem.json
Labels: enhancement

#383 src/components/routes: display new components in /routes path + add edit count
  src/components/__tests__/RouteListEdit.cy.js
  src/components/__tests__/RouteTabs.cy.js
  src/components/__tests__/RoutesApps.cy.js
  src/components/routes/RouteItemEdit.vue
  src/components/routes/RouteListEdit.vue
  src/components/routes/RouteTabs.vue
  src/components/routes/RoutesApps.vue
  src/components/types/Route.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  test/cypress/fixtures/routeList.json
Labels: enhancement

#388 src/pages: add Results Page with variants of content
  src/components/__tests__/ResultsChallengeOngoing.cy.js
  src/components/__tests__/ResultsChallengeUpcoming.cy.js
  src/components/homepage/CardChallenge.vue
  src/components/results/ResultsChallengeOngoing.vue
  src/components/results/ResultsChallengeUpcoming.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/mocks/layout.ts
  src/pages/ResultsPage.vue
  src/router/routes.ts
  src/router/routes_conf.ts
  test/cypress/e2e/results.spec.cy.js
Labels: enhancement

#389 src/components/results: add ResultsList component to be used in results detail view
  src/components/__tests__/CardProgress.cy.js
  src/components/__tests__/ResultsList.cy.js
  src/components/homepage/CardProgress.vue
  src/components/results/ResultsList.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: enhancement

#397 test/cypress/e2e: update test for routes
  test/cypress/e2e/routes.spec.cy.js
Labels: bug

#399 test/cypress/e2e: fix E2E test register_challenge translation string
  test/cypress/e2e/register_challenge.spec.cy.js
Labels: bug

#394 src/components/global: add component TableFilter for displaying data
  src/components/__tests__/TableFilter.cy.js
  src/components/global/TableFilter.vue
  src/components/types/Form.ts
  src/components/types/Table.ts
  src/composables/useTable.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  test/cypress/fixtures/tableResultsFilterRows.json
Labels: enhancement

#398 src/components/results: add component BannerChallengeDescription to display challenge details
  src/components/__tests__/BannerChallengeDescription.cy.js
  src/components/results/BannerChallengeDescription.vue
  src/components/types/Challenge.ts
  src/composables/useRoutes.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  test/cypress/fixtures/bannerChallengeDescription.json
Labels: enhancement

#401 src/components/global: add component ListCardSlider to render slider sections
  src/components/__tests__/ListCardSlider.cy.js
  src/components/global/ListCardSlider.vue
  src/components/types/Card.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/ResultsDetailPage.vue
  test/cypress/fixtures/listResultsPrizes.json
Labels: enhancement

#403 src/pages: add new CommunityPage component for displaying community news
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/mocks/layout.ts
  src/pages/CommunityPage.vue
  src/router/routes.ts
  src/router/routes_conf.ts
  test/cypress/e2e/community.spec.cy.js
  test/cypress/fixtures/listCardsEvent.json
Labels: enhancement
