Repository auto-mat/ride-to-work-by-bike-frontend, pull requests merged in 2024-01, with the labels that each got.

#168 test/cypress/e2e: use dynamic path for login tests + refactor lang switch test
  test/cypress/e2e/login.spec.cy.js
Labels: enhancement

#176 src/component: use email field component in form componets
  src/components/__tests__/FormLogin.cy.js
  src/components/__tests__/FormRegister.cy.js
  src/components/global/FormFieldEmail.vue
  src/components/login/FormLogin.vue
  src/components/register/FormRegister.vue
Labels: enhancement

#186 test/cypress/e2e: fix re-apply input widget lazy validation rules during component/e2e tests
  src/components/__tests__/FormFieldEmail.cy.js
  src/components/__tests__/FormFieldPhone.cy.js
  src/components/__tests__/FormRegister.cy.js
  src/components/__tests__/FormRegisterCoordinator.cy.js
  src/components/__tests__/HelpButton.cy.js
  src/components/__tests__/LoginRegisterHeader.cy.js
  src/components/global/ContactForm.vue
  src/components/global/FormFieldPhone.vue
  test/cypress/e2e/home.spec.cy.js
  test/cypress/e2e/login.spec.cy.js
Labels: bug, component tests, e2e tests, CI

#195 test/cypress/e2e: if 'allows user to scroll to top using the footer button' test fail skip it
  test/cypress/e2e/home.spec.cy.js
Labels: bug, e2e tests, CI

#198 src/pages: fix deployed RegisterChallengePage stepper component img URL
  src/pages/RegisterChallengePage.vue
  test/cypress/e2e/register_challenge.spec.cy.js
Labels: bug, deployed app

#191 src/components/global: scroll to top of the dialog after dialog state switch
  src/components/global/DialogStates.vue
Labels: bug

#192 src/components/global: add FormFieldTextRequired component
  src/components/__tests__/FormFieldTextRequired.cy.js
  src/components/__tests__/FormRegisterCoordinator.cy.js
  src/components/global/FormFieldTextRequired.vue
  src/components/global/FormFieldTextRequiredTest.vue
  src/components/register/FormRegisterCoordinator.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: enhancement

#214 components/register: fix variable name
  src/components/register/FormRegisterCoordinator.vue
Labels: bug

#209 src/components/global: add FormFieldCompany component
  src/components/__tests__/FormFieldCompany.cy.js
  src/components/__tests__/FormRegisterCoordinator.cy.js
  src/components/global/FormFieldCompany.vue
  src/components/global/FormFieldCompanyTest.vue
  src/components/register/FormRegisterCoordinator.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: enhancement

#208 src/components/global: add `FormFieldPassword`, `FormFieldPasswordConfirm` components
  src/components/__tests__/FormFieldPassword.cy.js
  src/components/__tests__/FormFieldPasswordConfirm.cy.js
  src/components/__tests__/FormRegisterCoordinator.cy.js
  src/components/global/FormFieldPassword.vue
  src/components/global/FormFieldPasswordConfirm.vue
  src/components/global/FormFieldTestWrapper.vue
  src/components/register/FormRegisterCoordinator.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: enhancement

#217 components/global: use `FormFieldEmail` component across all forms
  src/components/__tests__/ContactForm.cy.js
  src/components/__tests__/HelpButton.cy.js
  src/components/__tests__/LoginRegisterHeader.cy.js
  src/components/global/ContactForm.vue
  src/components/global/FormFieldEmail.vue
  test/cypress/e2e/home.spec.cy.js
  test/cypress/e2e/login.spec.cy.js
Labels: enhancement

#218 components/global: use `FormFieldTextRequired` component in `ContactForm` component
  src/components/__tests__/ContactForm.cy.js
  src/components/__tests__/HelpButton.cy.js
  src/components/__tests__/LoginRegisterHeader.cy.js
  src/components/global/ContactForm.vue
  test/cypress/e2e/home.spec.cy.js
  test/cypress/e2e/login.spec.cy.js
Labels: enhancement

#224 __tests__: use common testing wrapper for FormField elements
  src/components/__tests__/FormFieldCompany.cy.js
  src/components/__tests__/FormFieldEmail.cy.js
  src/components/__tests__/FormFieldPhone.cy.js
  src/components/__tests__/FormFieldTextRequired.cy.js
  src/components/global/FormFieldCompanyTest.vue
  src/components/global/FormFieldEmailTest.vue
  src/components/global/FormFieldPhoneTest.vue
  src/components/global/FormFieldTestWrapper.vue
  src/components/global/FormFieldTextRequiredTest.vue
Labels: enhancement

#227 src/css/form: add global border radius style
  src/components/global/ContactForm.vue
  src/components/global/FormFieldCompany.vue
  src/components/global/FormFieldPassword.vue
  src/components/global/FormFieldPasswordConfirm.vue
  src/components/global/FormFieldTextRequired.vue
  src/components/login/FormLogin.vue
  src/components/register/FormRegister.vue
  src/components/register/FormRegisterCoordinator.vue
  src/css/app.scss
  src/css/form.scss
Labels: enhancement

#235 components/global: add root wrapper div to pass attributes to
  src/components/global/HelpButton.vue
Labels: bug

#236 components/form: add `FormPersonalDetails` component
  src/components/__tests__/FormPersonalDetails.cy.js
  src/components/form/FormPersonalDetails.vue
  src/components/types/Form.ts
  src/composables/useStepperValidation.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/RegisterChallengePage.vue
  test/cypress/e2e/register_challenge.spec.cy.js
Labels: enhancement

#237 coponents/form: add `FormFieldOptionGroup` component
  src/components/__tests__/FormFieldOptionGroup.cy.js
  src/components/form/FormFieldOptionGroup.vue
  src/components/global/FormFieldTestWrapper.vue
  src/components/types/Form.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: enhancement

#239 src/pages: add `FormFieldOptionGroup` to form step Participation
  src/components/form/FormFieldOptionGroup.vue
  src/composables/useStepperValidation.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/RegisterChallengePage.vue
  test/cypress/e2e/register_challenge.spec.cy.js
Labels: enhancement

#241 components/form: add company select widget for 4th step registration challenge
  src/components/__tests__/FormFieldCompanySelect.cy.js
  src/components/form/FormFieldCompanySelect.vue
  src/components/global/FormFieldTestWrapper.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/RegisterChallengePage.vue
Labels: enhancement

#242 components/global: add DialogForm component for displaying forms in a modal
  src/components/__tests__/FormFieldCompany.cy.js
  src/components/global/DialogDefault.vue
  src/components/global/FormFieldCompany.vue
  src/components/homepage/CardEvent.vue
  src/components/homepage/CardOffer.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: enhancement
