Repository auto-mat/ride-to-work-by-bike-frontend, pull requests merged in 2025-01, with the labels that each got.

#812 src/components/register: add component EmailConfirmation
  ride_to_work_by_bike_config.toml
  src/components/register/EmailConfirmation.vue
  src/components/types/Config.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/ConfirmEmailPage.vue
  src/router/index.ts
  src/router/routes.ts
  src/router/routes_conf.ts
  src/stores/register.ts
Labels: enhancement

#811 src/stores/registerChallenge: add register-challenge API calls for saving and retrieving registration state
  ride_to_work_by_bike_config.toml
  src/adapters/registerChallengeAdapter.ts
  src/components/enums/RegisterChallenge.ts
  src/components/form/FormFieldListMerch.vue
  src/components/types/ApiRegistration.ts
  src/components/types/Config.ts
  src/components/types/Newsletter.ts
  src/components/types/Profile.ts
  src/components/types/RegisterChallenge.ts
  src/composables/useApiGetRegisterChallenge.ts
  src/composables/useApiPostRegisterChallenge.ts
  src/composables/useStepperValidation.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/RegisterChallengePage.vue
  src/stores/registerChallenge.ts
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/apiGetRegisterChallenge.json
  test/cypress/fixtures/apiGetRegisterChallengeEmpty.json
  test/cypress/fixtures/apiPostRegisterChallengeMerchandiseRequest.json
  test/cypress/fixtures/apiPostRegisterChallengePaymentRequest.json
  test/cypress/fixtures/apiPostRegisterChallengePersonalDetailsRequest.json
  test/cypress/fixtures/apiPostRegisterChallengeResponse.json
  test/cypress/fixtures/apiPostRegisterChallengeTeamRequest.json
  test/cypress/support/commands.js
Labels: enhancement

#817 src/components/global: fix displaying select value after reload in FormFieldCompany component
  src/components/__tests__/FormFieldCompany.cy.js
  src/components/global/FormFieldCompany.vue
  test/cypress/e2e/register_challenge.spec.cy.js
Labels: enhancement

#818 src/components: fix FormFieldListMerch validation by correctly clearing value after no-merch uncheck
  src/components/form/FormFieldListMerch.vue
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/apiGetMerchandiseResponseNone.json
  test/cypress/support/commands.js
Labels: bug

#815 src/stores: add ability to create a new payment order via functions in registerChallenge store
  ride_to_work_by_bike_config.toml
  src/adapters/payuAdapter.ts
  src/adapters/registerChallengeAdapter.ts
  src/components/debug/ShowOrganizationIds.vue
  src/components/enums/Api.ts
  src/components/enums/Payment.ts
  src/components/form/FormFieldVoucher.vue
  src/components/register/RegisterChallengePayment.vue
  src/components/types/ApiIpAddress.ts
  src/components/types/ApiPayu.ts
  src/components/types/Config.ts
  src/composables/useApi.ts
  src/composables/useApiGetIpAddress.ts
  src/composables/useApiPostPayuCreateOrder.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/RegisterChallengePage.vue
  src/stores/challenge.ts
  src/stores/registerChallenge.ts
  src/utils/price_levels.ts
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/apiGetIpAddressResponse.json
  test/cypress/fixtures/apiGetRegisterChallengeCompanyNoAdmission.json
  test/cypress/fixtures/apiGetRegisterChallengeCompanyWaiting.json
  test/cypress/fixtures/apiGetRegisterChallengeIndividualNotPaid.json
  test/cypress/fixtures/apiGetRegisterChallengeIndividualPaid.json
  test/cypress/fixtures/apiPostPayuCreateOrderRequest.json
  test/cypress/fixtures/apiPostPayuCreateOrderRequestCompanyWithDonation.json
  test/cypress/fixtures/apiPostPayuCreateOrderRequestIndividualNoDonation.json
  test/cypress/fixtures/apiPostPayuCreateOrderRequestIndividualWithDonation.json
  test/cypress/fixtures/apiPostPayuCreateOrderRequestSchoolWithDonation.json
  test/cypress/fixtures/apiPostPayuCreateOrderRequestVoucherFullWithDonation.json
  test/cypress/fixtures/apiPostPayuCreateOrderRequestVoucherHalfNoDonation.json
  test/cypress/fixtures/apiPostPayuCreateOrderRequestVoucherHalfWithDonation.json
  test/cypress/fixtures/apiPostPayuCreateOrderResponse.json
  test/cypress/fixtures/apiPostPayuCreateOrderResponseNoRedirect.json
  test/cypress/support/commands.js
Labels: enhancement

#822 src/components: add logic to show selected no-merch option in FormFieldListMerch if loaded from API
  src/components/form/FormFieldListMerch.vue
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/apiGetRegisterChallengeNoMerch.json
  test/cypress/support/commands.js
Labels: bug

#824 test/cypress: add e2e tests for confirm-email endpoint
  src/components/register/EmailConfirmation.vue
  test/cypress/e2e/confirm_email.spec.cy.js
  test/cypress/fixtures/apiGetConfirmEmailResponseFail.json
  test/cypress/fixtures/apiGetConfirmEmailResponseOK.json
  test/cypress/support/commands.js
Labels: enhancement

#827 test/cypress: remove duplicate interceptVerifyEmailApi command
  test/cypress/support/commands.js
Labels: bug

#829 src/composables: fix refreshing access token, if token is not available before every REST API call
  src/boot/pinia.js
  src/composables/useApiGetCampaign.ts
  src/composables/useApiGetCities.ts
  src/composables/useApiGetDiscountCoupon.ts
  src/composables/useApiGetFilteredMerchandise.ts
  src/composables/useApiGetHasOrganizationAdmin.ts
  src/composables/useApiGetMerchandise.ts
  src/composables/useApiGetOrganizations.ts
  src/composables/useApiGetRegisterChallenge.ts
  src/composables/useApiGetSubsidiaries.ts
  src/composables/useApiGetTeams.ts
  src/composables/useApiPostOrganization.ts
  src/composables/useApiPostPayuCreateOrder.ts
  src/composables/useApiPostRegisterChallenge.ts
  src/composables/useApiPostSubsidiary.ts
  src/composables/useApiPostTeam.ts
  src/stores/login.ts
  src/stores/register.ts
  test/cypress/e2e/login.spec.cy.js
Labels: bug

#826 src/stores: update API call to register coordinator and use it in register-challenge
  ride_to_work_by_bike_config.toml
  src/adapters/newsletterAdapter.ts
  src/adapters/registerChallengeAdapter.ts
  src/adapters/registerCoordinatorAdapter.ts
  src/components/__tests__/FormRegisterCoordinator.cy.js
  src/components/register/FormRegisterCoordinator.vue
  src/components/register/RegisterChallengePayment.vue
  src/components/types/Register.ts
  src/components/types/RegisterChallenge.ts
  src/composables/useStepperValidation.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/stores/register.ts
  src/stores/registerChallenge.ts
  src/utils/index.ts
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/e2e/register_coordinator.spec.cy.js
  test/cypress/fixtures/apiPostRegisterCoordinatorRequest.json
  test/cypress/support/commands.js
  test/cypress/support/commonTests.ts
Labels: enhancement

#828 src/pages: show button loader when updating registration via API in RegisterChallengePage
  src/pages/RegisterChallengePage.vue
  src/stores/registerChallenge.ts
  test/cypress/e2e/register_challenge.spec.cy.js
Labels: enhancement

#830 src/composables: add new dynamic translation strings to useOrganizations
  src/components/__tests__/FormAddCompany.cy.js
  src/components/__tests__/FormAddSubsidiary.cy.js
  src/components/__tests__/FormFieldCompanyAddress.cy.js
  src/components/__tests__/RegisterChallengePayment.cy.js
  src/components/form/FormAddCompany.vue
  src/components/form/FormAddSubsidiary.vue
  src/components/form/FormFieldCompanyAddress.vue
  src/components/register/RegisterChallengePayment.vue
  src/composables/useOrganizations.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: bug

#831 src/stores: connect fields telephone and telephoneOptIn to registerChallenge store and API request
  src/adapters/registerChallengeAdapter.ts
  src/components/__tests__/FormFieldListMerch.cy.js
  src/components/form/FormFieldListMerch.vue
  src/components/types/ApiRegistration.ts
  src/components/types/RegisterChallenge.ts
  src/stores/registerChallenge.ts
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/apiGetRegisterChallengeCompanyWaiting.json
  test/cypress/fixtures/apiPostRegisterChallengeMerchandiseRequest.json
  test/cypress/support/commands.js
  test/cypress/support/commonTests.ts
Labels: enhancement

#835 src/components: scroll to initially selected item after loading options in FormFieldSelectTable
  src/components/form/FormFieldSelectTable.vue
Labels: enhancement

#836 src/composables: update phone validation regex in useValidation to be less strict
  src/components/__tests__/FormFieldPhone.cy.js
  src/composables/useValidation.ts
  test/cypress/e2e/register_challenge.spec.cy.js
Labels: enhancement

#837 src/stores: add API check to see if user is coordinator to show/hide register coordinator checkbox
  ride_to_work_by_bike_config.toml
  src/components/__tests__/RegisterChallengePayment.cy.js
  src/components/register/RegisterChallengePayment.vue
  src/components/types/Config.ts
  src/composables/useApiIsUserOrganizationAdmin.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/stores/registerChallenge.ts
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/apiGetIsUserOrganizationAdminResponseFalse.json
  test/cypress/fixtures/apiGetIsUserOrganizationAdminResponseTrue.json
  test/cypress/support/commands.js
Labels: enhancement

#841 src/pages: submit voucher data to register-challenge endpoint before creating a PayU order
  src/pages/RegisterChallengePage.vue
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/apiPostRegisterChallengeVoucherFullRequest.json
Labels: enhancement

#843 test/cypress/e2e: update register_challenge test for resetting IDs on parent data change
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/formOrganizationOptions.json
Labels: bug

#844 src/stores: postpone submitting payment data if payment subject is company
  src/components/__tests__/RegisterChallengePayment.cy.js
  src/components/register/RegisterChallengePayment.vue
  src/components/register/RegisterChallengePaymentMessages.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/stores/registerChallenge.ts
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/apiPostRegisterChallengeTeamCompanyPaymentRequest.json
Labels: enhancement

#845 src/components: add autocomplete functionality to FormFieldCompanyAddress
  src/components/__tests__/FormFieldCompanyAddress.cy.js
  src/components/form/FormFieldCompanyAddress.vue
  src/components/form/FormSelectOrganization.vue
  src/components/global/FormFieldCompany.vue
  src/composables/useSelectSearch.ts
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/apiGetSubsidiariesResponse.json
  test/cypress/support/commands.js
Labels: enhancement

#846 src/adapters: add adapter for GET subsidiary data to correctly display full address
  src/adapters/subsidiaryAdapter.ts
  src/components/types/ApiSubsidiary.ts
  src/composables/useApiGetSubsidiaries.ts
  test/cypress/support/commands.js
Labels: bug

#852 src/stores: add payment_category and products to API POST request for organization payment
  src/adapters/registerChallengeAdapter.ts
  src/components/types/ApiRegistration.ts
  src/stores/registerChallenge.ts
  test/cypress/fixtures/apiPostRegisterChallengeTeamCompanyPaymentRequest.json
Labels: enhancement

#853 src/i18n: add translated messages for API getHasOrganizationAdmin
  src/components/__tests__/RegisterChallengePayment.cy.js
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: bug

#859 src/i18n: update labels on login buttons
  src/i18n/en.toml
Labels: bug

#858 src/components: add link to personal data protection policy to FormPersonalDetails
  src/components/__tests__/FormPersonalDetails.cy.js
  src/components/form/FormPersonalDetails.vue
Labels: bug

#860 src/components: update merch category label unisex in FormFieldListMerch
  src/components/__tests__/FormFieldListMerch.cy.js
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: enhancement

#857 test/cypress/e2e: wait for subsidiaries before accessing select values to avoid no results failure
  test/cypress/e2e/register_challenge.spec.cy.js
Labels: bug

#856 src/stores: fix issue where registration could not be completed for voucher with 100% discount
  src/components/types/ApiRegistration.ts
  src/stores/registerChallenge.ts
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/apiPostRegisterChallengeResponse.json
  test/cypress/fixtures/apiPostRegisterChallengeResponsePaymentDone.json
  test/cypress/fixtures/apiPostRegisterChallengeResponsePaymentNoAdmission.json
  test/cypress/fixtures/apiPostRegisterChallengeResponsePaymentNone.json
  test/cypress/fixtures/apiPostRegisterChallengeResponsePaymentUnknown.json
  test/cypress/fixtures/apiPostRegisterChallengeResponsePaymentWaiting.json
  test/cypress/support/commands.js
Labels: bug

#855 public/favicon: update favicon to RTWBB logo
  public/favicon.ico
  public/icons/favicon-128x128.png
  public/icons/favicon-16x16.png
  public/icons/favicon-32x32.png
  public/icons/favicon-96x96.png
Labels: enhancement

#851 src/components: connect CountdownEvent component to challenge phase set data
  ride_to_work_by_bike_config.toml
  src/components/global/TopBarCountdown.vue
  src/components/homepage/CountdownChallenge.vue
  src/components/homepage/CountdownEvent.vue
  src/composables/useCountdown.ts
  src/pages/IndexPage.vue
  src/stores/challenge.ts
  src/utils/index.ts
  test/cypress/e2e/home.spec.cy.js
Labels: enhancement

#850 src/components: display phone field in FormFieldListMerch component when no-merch option is selected
  src/components/__tests__/FormFieldListMerch.cy.js
  src/components/form/FormFieldListMerch.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  test/cypress/e2e/register_challenge.spec.cy.js
Labels: bug

#862 src/composables: validate register challenge submitStep responses before allowing to continue
  src/composables/useStepperValidation.ts
  src/stores/registerChallenge.ts
  test/cypress/e2e/register_challenge.spec.cy.js
Labels: bug

#861 src/stores: clear registerChallenge persistent store properties after logout
  src/stores/login.ts
  src/stores/registerChallenge.ts
  src/utils/get_register_challenge_empty_state.ts
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/e2e/register_challenge_storage.spec.cy.js
  test/cypress/fixtures/registerChallengeLocalStorageCompletedVoucherFull.json
  test/cypress/support/commands.js
Labels: bug

#864 src/pages: add ResetPasswordPage with password reset functionality
  public/icons/reset_password/icons.svg
  ride_to_work_by_bike_config.toml
  src/components/__tests__/FormLogin.cy.js
  src/components/__tests__/ResetPassword.cy.js
  src/components/login/FormLogin.vue
  src/components/register/ResetPassword.vue
  src/components/types/ApiResetPassword.ts
  src/components/types/Config.ts
  src/composables/useApiPostResetPasswordConfirm.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/ResetPasswordPage.vue
  src/router/index.ts
  src/router/routes.ts
  src/router/routes_conf.ts
  test/cypress/e2e/confirm_email.spec.cy.js
  test/cypress/e2e/reset_password.spec.cy.js
  test/cypress/e2e/router_rules.cy.js
  test/cypress/fixtures/apiPostResetPasswordConfirmRequest.json
  test/cypress/fixtures/apiPostResetPasswordConfirmResponseSuccess.json
  test/cypress/fixtures/confirmEmailAddressParams.json
  test/cypress/support/commands.js
Labels: enhancement

#865 src/components: add notification messages for registration step summary
  src/components/__tests__/RegisterChallengePaymentMessages.cy.js
  src/components/register/RegisterChallengePaymentMessages.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/RegisterChallengePage.vue
  test/cypress/e2e/register_challenge.spec.cy.js
Labels: bug

#866 src/components: update postcode validation in FormAddSubsidiary
  src/components/__tests__/FormAddSubsidiary.cy.js
  src/components/form/FormAddSubsidiary.vue
  src/composables/useValidation.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: bug

#867 src/components: disable other company options than the selected when payment subject is company
  src/components/form/FormFieldCompanyAddress.vue
  src/components/form/FormFieldSelectTable.vue
  src/components/register/RegisterChallengePayment.vue
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/support/commands.js
  test/cypress/support/commonTests.ts
Labels: bug

#869 src/stores: enable access to register coordinator section
  src/components/__tests__/FormPersonalDetails.cy.js
  src/components/__tests__/FormRegisterCoordinator.cy.js
  src/components/form/FormPersonalDetails.vue
  src/components/register/RegisterChallengePayment.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/RegisterChallengePage.vue
  src/pages/RegisterCoordinatorPage.vue
  src/router/index.ts
  src/stores/login.ts
  src/stores/register.ts
  src/stores/registerChallenge.ts
  src/utils/get_register_challenge_empty_state.ts
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/e2e/register_challenge_storage.spec.cy.js
  test/cypress/e2e/register_coordinator.spec.cy.js
  test/cypress/e2e/router_rules.cy.js
  test/cypress/fixtures/registerChallengeLocalStorageCompletedVoucherFull.json
  test/cypress/support/commands.js
Labels: enhancement

#873 test/cypress/e2e: fix issue in register_coordinator e2e test missing an intercept
  test/cypress/e2e/register_coordinator.spec.cy.js
Labels: bug

#876 src/components/__tests__: fix subsidiary ZIP form field placeholder mask
  src/components/__tests__/FormFieldSelectTable.cy.js
Labels: bug

#879 src/components/__tests__: fix setting register challange isUserOrganizationAdmin store value
  src/components/__tests__/RegisterChallengePayment.cy.js
Labels: bug, component tests

#880 src/components/__tests__: fix checking subsidiary form field street address
  src/components/__tests__/FormSelectOrganization.cy.js
Labels: bug, component tests

#878 src/components/global: add automat logo to LoginRegisterHeader and MainLayout sidebar
  ride_to_work_by_bike_config.toml
  src/assets/svg/logo-automat-white.svg
  src/assets/svg/logo-automat.svg
  src/components/__tests__/AutomatLogo.cy.js
  src/components/__tests__/AutomatLogoBanner.cy.js
  src/components/__tests__/LoginRegisterHeader.cy.js
  src/components/global/AutomatLogo.vue
  src/components/global/AutomatLogoBanner.vue
  src/components/global/LoginRegisterHeader.vue
  src/components/types/Config.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/layouts/MainLayout.vue
  test/cypress/support/commonTests.ts
Labels: enhancement

#881 src/stores: update call point for checkOrganizationHasCoordinator func to remove unnecessary API request
  cypress.config.js
  src/components/__tests__/RegisterChallengePayment.cy.js
  src/components/register/RegisterChallengePayment.vue
  src/stores/registerChallenge.ts
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/registerChallengeLocalStorageCompletedVoucherFull.json
Labels: bug

#875 src/component: override form fields validation error color with custom color
  ride_to_work_by_bike_config.toml
  src/boot/global_vars.ts
  src/components/__tests__/FormFieldEmail.cy.js
  src/components/__tests__/FormLogin.cy.js
  src/components/__tests__/FormRegister.cy.js
  src/components/__tests__/ResetPassword.cy.js
  src/components/global/FormFieldEmail.vue
  src/components/global/FormFieldTestWrapper.vue
  src/components/login/FormLogin.vue
  src/components/register/FormRegister.vue
  src/components/register/ResetPassword.vue
  src/components/types/Config.ts
  src/css/form.scss
  src/css/quasar.variables.scss
  src/pages/LoginPage.vue
  src/pages/RegisterPage.vue
  src/pages/ResetPasswordPage.vue
  src/utils/index.ts
  test/cypress/e2e/login.spec.cy.js
  test/cypress/e2e/register.spec.cy.js
  test/cypress/e2e/reset_password.spec.cy.js
  test/cypress/support/commands.js
Labels: enhancement

#874 src/stores: update processing voucher on load and registration-complete condition
  src/stores/registerChallenge.ts
Labels: bug

#871 src/components: add ability to submit forms by pressing enter
  src/components/form/FormFieldCompanyAddress.vue
  src/components/form/FormFieldSelectTable.vue
  src/components/form/FormFieldVoucher.vue
  src/components/global/FormFieldCompany.vue
  src/components/register/FormRegisterCoordinator.vue
  test/cypress/e2e/register_challenge.spec.cy.js
Labels: enhancement

#882 src/router: make routing use the registration phase interval instead of challenge phase interval
  src/components/__tests__/FormRegister.cy.js
  src/router/index.ts
  test/cypress/e2e/challenge_inactive.spec.cy.js
  test/cypress/e2e/home.spec.cy.js
  test/cypress/e2e/register.spec.cy.js
  test/cypress/e2e/router_rules.cy.js
  test/cypress/support/commonTests.ts
Labels: enhancement

#883 src/i18n: update default language and add saving language to backend during registration
  src/adapters/registerChallengeAdapter.ts
  src/components/__tests__/LanguageSwitcher.cy.js
  src/components/global/LanguageSwitcher.vue
  src/components/types/ApiRegistration.ts
  src/i18n/def_locale.js
  src/stores/registerChallenge.ts
  src/utils/get_api_base_url_with_lang.ts
  src/utils/get_register_challenge_empty_state.ts
  test/cypress/fixtures/apiPostRegisterChallengePersonalDetailsRequest.json
  test/cypress/support/commonTests.ts
Labels: enhancement

#885 src/components: update data for compnent ListCardFollow to show AutoMat Facebook profile
  public/image/facebook-profile-automat.webp
  ride_to_work_by_bike_config.toml
  src/components/__tests__/ListCardFollow.cy.js
  src/components/homepage/CardFollow.vue
  src/components/homepage/ListCardFollow.vue
  src/components/types/Config.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/IndexPage.vue
  test/cypress/e2e/home.spec.cy.js
Labels: enhancement

#886 src/adapters: allow to submit empty newsletter field to register challenge POST API
  src/adapters/registerChallengeAdapter.ts
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/apiPostRegisterChallengePersonalDetailsChallengeNewsletter.json
  test/cypress/fixtures/apiPostRegisterChallengePersonalDetailsNoNewsletter.json
Labels: bug

#877 src/components: update ProfileDetails component to show data from store and allow updates
  src/adapters/registerChallengeAdapter.ts
  src/components/__tests__/FormUpdateEmail.cy.js
  src/components/__tests__/FormUpdateGender.cy.js
  src/components/__tests__/FormUpdateNickname.cy.js
  src/components/__tests__/ProfileDetails.cy.js
  src/components/__tests__/ProfileTabs.cy.js
  src/components/form/FormUpdateEmail.vue
  src/components/form/FormUpdateGender.vue
  src/components/form/FormUpdateNickname.vue
  src/components/profile/ProfileDetails.vue
  src/components/profile/ProfileTabs.vue
  src/components/types/ApiRegistration.ts
  src/components/types/RegisterChallenge.ts
  src/composables/useApiPutRegisterChallenge.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/stores/registerChallenge.ts
  src/utils/get_gender_label.ts
  src/utils/get_register_challenge_empty_state.ts
  test/cypress/e2e/profile.spec.cy.js
  test/cypress/fixtures/apiGetRegisterChallengeProfile.json
  test/cypress/fixtures/apiGetRegisterChallengeProfileNoMerch.json
  test/cypress/fixtures/apiGetRegisterChallengeProfileUpdatedGender.json
  test/cypress/fixtures/apiGetRegisterChallengeProfileUpdatedNickname.json
  test/cypress/fixtures/apiGetRegisterChallengeProfileUpdatedTelephoneOptIn.json
  test/cypress/fixtures/registerChallengeLocalStorageCompletedVoucherFull.json
  test/cypress/support/commands.js
Labels: enhancement

#887 src/stores: clear voucher on step change if payment subject is not voucher
  src/adapters/registerChallengeAdapter.ts
  src/stores/registerChallenge.ts
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/apiPostRegisterChallengeVoucherNoneRequest.json
Labels: bug

#889 src/components: make privacy policy link in RegisterChallengePayment coordinator form clickable
  src/components/__tests__/RegisterChallengePayment.cy.js
  src/components/register/RegisterChallengePayment.vue
Labels: bug

#891 src/components: make privacy policy link in FormRegisterCoordinator coordinator form clickable
  src/components/__tests__/FormRegisterCoordinator.cy.js
  src/components/register/FormRegisterCoordinator.vue
Labels: bug

#890 src/components: save language on selection in LanguageSwitcher component
  src/adapters/registerChallengeAdapter.ts
  src/components/__tests__/LanguageSwitcher.cy.js
  src/components/global/LanguageSwitcher.vue
  test/cypress/fixtures/apiGetRegisterChallengeProfileLanguageEn.json
  test/cypress/fixtures/apiGetRegisterChallengeProfileLanguageSk.json
  test/cypress/fixtures/apiPostRegisterChallengeLanguageEn.json
  test/cypress/fixtures/apiPostRegisterChallengeLanguageSk.json
Labels: enhancement

#892 src/components/global: add social media login/register buttons hint text
  src/components/__tests__/LoginRegisterButtons.cy.js
  src/components/global/LoginRegisterButtons.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: enhancement

#888 src/components: add ability to subscribe to different newsletter via NewsletterFeature component
  src/assets/image/newsletter-feature/newsletter.webp
  src/components/__tests__/NewsletterFeature.cy.js
  src/components/__tests__/NewsletterItem.cy.js
  src/components/homepage/NewsletterFeature.vue
  src/components/homepage/NewsletterItem.vue
  src/components/types/Newsletter.ts
  src/mocks/homepage.ts
  test/cypress/fixtures/apiGetRegisterChallengeProfileUpdatedNewsletter.json
  test/cypress/fixtures/apiGetRegisterChallengeProfileUpdatedNewsletterAll.json
  test/cypress/fixtures/apiPostRegisterChallengeNewsletterAllRequest.json
  test/cypress/fixtures/apiPostRegisterChallengeNewsletterChallengeMobilityRequest.json
  test/cypress/support/commands.js
Labels: enhancement

#893 src/pages: remove dummy posts from ChallengeInactivePage
  src/pages/ChallengeInactivePage.vue
  test/cypress/e2e/challenge_inactive.spec.cy.js
Labels: enhancement

#895 src/components: update data source for TopBarCountdown to show correct countdown on register-challenge page
  src/components/__tests__/TopBarCountdown.cy.js
  src/components/global/TopBarCountdown.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/RegisterChallengePage.vue
  test/cypress/e2e/register_challenge.spec.cy.js
Labels: bug

#896 src/components/form: fix removing space from the typed discount coupon string
  src/components/form/FormFieldVoucher.vue
  test/cypress/support/commands.js
Labels: bug

#897 src/components/register: fix switching payment subject radio buttons translated labels
  src/components/__tests__/RegisterChallengePayment.cy.js
  src/components/register/RegisterChallengePayment.vue
Labels: bug

#898 src/mocks: fix getting global app config in Cypress e2e tests
  src/components/__tests__/DrawerMenu.cy.js
  src/components/global/MobileBottomPanel.vue
  src/layouts/MainLayout.vue
  src/mocks/layout.ts
  test/cypress/e2e/community.spec.cy.js
  test/cypress/support/commonTests.ts
Labels: bug

#899 src/components/register: fix showing accept data privacy policy checkbox element
  src/components/__tests__/FormRegister.cy.js
  src/components/register/FormRegister.vue
  test/cypress/e2e/register.spec.cy.js
Labels: bug

#901 src/components: add terms of service link to personal details checkbox in FormPersonalDetails
  ride_to_work_by_bike_config.toml
  src/components/__tests__/FormPersonalDetails.cy.js
  src/components/form/FormPersonalDetails.vue
  src/components/types/Config.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: enhancement

#903 src/utils: fix and extend getCurrentPriceLevelsUtilTestData() func by unit tests
  src/utils/price_levels.ts
  test/cypress/e2e/unit_utils_tests.cy.js
  test/cypress/fixtures/getCurrentPriceLevelsUtilTestData.json
Labels: bug

#902 config: update registration payment mid prices values
  ride_to_work_by_bike_config.toml
  src/components/__tests__/RegisterChallengePayment.cy.js
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/apiPostPayuCreateOrderRequest.json
  test/cypress/fixtures/apiPostPayuCreateOrderRequestIndividualWithDonation.json
  test/cypress/fixtures/apiPostPayuCreateOrderRequestVoucherHalfWithDonation.json
Labels: enhancement
