Repository auto-mat/ride-to-work-by-bike-frontend, pull requests merged in 2025-02, with the labels that each got.

#904 src/i18n: update i18n translation files
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: enhancement

#905 src/components: update CountdownEvent component title to correctly show challenge month
  src/components/__tests__/CountdownEvent.cy.js
  src/components/homepage/CountdownEvent.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  test/cypress/e2e/home.spec.cy.js
Labels: bug

#906 src/adapters: add missing rounding function for coupon discount calculation
  src/adapters/payuAdapter.ts
  src/components/register/RegisterChallengePayment.vue
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/apiGetDiscountCouponResponse95.json
  test/cypress/fixtures/apiGetThisCampaignMay.json
  test/cypress/fixtures/apiPostPayuCreateOrderRequestVoucher95NoDonation.json
  test/cypress/support/commands.js
  test/cypress/support/commonTests.ts
Labels: bug

#907 src/utils: fix getting current price level calculation
  src/utils/price_levels.ts
  test/cypress/e2e/unit_utils_tests.cy.js
  test/cypress/fixtures/getCurrentPriceLevelsUtilTestData.json
Labels: bug, e2e tests

#908 src/stores: load coupon on register challenge refresh in registerChallenge store
  src/components/register/RegisterChallengePayment.vue
  src/stores/registerChallenge.ts
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/apiGetRegisterChallengeVoucher95NotApplied.json
Labels: bug

#909 test/cypress/e2e: fix Cypress company_coordinator e2e 'displays company coordinator disabled text' test
  test/cypress/e2e/company_coordinator.spec.cy.js
Labels: bug, e2e tests

#910 src/components/form: add merchandise size conversion chart URL link
  ride_to_work_by_bike_config.toml
  src/components/__tests__/FormFieldListMerch.cy.js
  src/components/form/FormFieldListMerch.vue
  src/components/types/Config.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  test/cypress/e2e/register_challenge.spec.cy.js
Labels: enhancement

#913 src/components: inject global app config vars with localization lang code
  ride_to_work_by_bike_config.toml
  src/components/__tests__/AutomatLogo.cy.js
  src/components/__tests__/DrawerMenu.cy.js
  src/components/__tests__/FooterBar.cy.js
  src/components/__tests__/FormPersonalDetails.cy.js
  src/components/__tests__/FormRegister.cy.js
  src/components/__tests__/FormRegisterCoordinator.cy.js
  src/components/__tests__/ListCardPost.cy.js
  src/components/__tests__/MenuLinks.cy.js
  src/components/__tests__/RegisterChallengePayment.cy.js
  src/components/form/FormPersonalDetails.vue
  src/components/global/AutomatLogo.vue
  src/components/global/FooterBar.vue
  src/components/global/MobileBottomPanel.vue
  src/components/homepage/ListCardPost.vue
  src/components/register/FormRegister.vue
  src/components/register/FormRegisterCoordinator.vue
  src/components/register/RegisterChallengePayment.vue
  src/composables/useUsefulLinks.ts
  src/layouts/MainLayout.vue
Labels: enhancement

#912 src/composables: add useMenu composable to handle conditional display of coordinator link
  ride_to_work_by_bike_config.toml
  src/components/__tests__/DrawerMenu.cy.js
  src/components/global/MobileBottomPanel.vue
  src/components/types/Config.ts
  src/composables/useMenu.ts
  src/layouts/MainLayout.vue
  src/mocks/layout.ts
  src/pages/IndexPage.vue
  test/cypress/e2e/community.spec.cy.js
  test/cypress/e2e/home.spec.cy.js
  test/cypress/support/commands.js
  test/cypress/support/commonTests.ts
Labels: enhancement

#914 src/components: inject global app config var with localization lang code
  src/pages/CompanyCoordinatorPage.vue
Labels: enhancement

#915 src/mocks: update newsletter items list to computed value to show dynamically translated labels
  src/components/__tests__/NewsletterItem.cy.js
  src/components/homepage/NewsletterFeature.vue
  src/components/types/Newsletter.ts
  src/mocks/homepage.ts
  test/cypress/e2e/home.spec.cy.js
Labels: bug

#916 src/i18n: update translation strings
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
Labels: enhancement

#917 src/components: allow updating user phone number in ProfileDetails component
  src/components/__tests__/FormUpdatePhone.cy.js
  src/components/__tests__/ProfileDetails.cy.js
  src/components/form/FormUpdatePhone.vue
  src/components/profile/ProfileDetails.vue
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  test/cypress/e2e/profile.spec.cy.js
  test/cypress/fixtures/apiGetRegisterChallengeProfileUpdatedTelephone.json
Labels: enhancement

#919 src/composables: fix email form field validation letter case insensitive rule
  src/components/__tests__/FormFieldEmail.cy.js
  src/composables/useValidation.ts
Labels: enhancement

#920 src/composables: add Django admin menu link item into home page menu
  public/icons/drawer_menu/icons.svg
  ride_to_work_by_bike_config.toml
  src/adapters/registerChallengeAdapter.ts
  src/components/__tests__/DrawerMenu.cy.js
  src/components/global/MobileBottomPanel.vue
  src/components/types/ApiRegistration.ts
  src/components/types/Config.ts
  src/components/types/RegisterChallenge.ts
  src/composables/useMenu.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/layouts/MainLayout.vue
  src/stores/registerChallenge.ts
  src/utils/get_register_challenge_empty_state.ts
  test/cypress/e2e/home.spec.cy.js
  test/cypress/fixtures/apiGetRegisterChallengeIndividualPaidCompleteStaff.json
  test/cypress/fixtures/registerChallengeLocalStorageCompletedVoucherFull.json
  test/cypress/support/commands.js
  test/cypress/support/commonTests.ts
Labels: enhancement

#923 src/adapters: update loaded properties of discount coupon to correctly load one-time coupons
  src/adapters/couponAdapter.ts
  src/components/form/FormFieldVoucher.vue
  src/components/types/Coupon.ts
  src/stores/registerChallenge.ts
  test/cypress/e2e/register_challenge.spec.cy.js
  test/cypress/fixtures/apiGetDiscountCouponResponseOneTime.json
  test/cypress/fixtures/registerChallengeLocalStorageCompletedVoucherFull.json
Labels: bug

#928 src/composables: fix merchandise images absolute URL path on the localhost
  src/components/__tests__/FormCardMerch.cy.js
  src/components/form/FormCardMerch.vue
  src/composables/useApiGetMerchandise.ts
  src/stores/registerChallenge.ts
  src/utils/index.ts
  test/cypress/fixtures/cardMerchLocalhost.json
Labels: bug

#925 src/components: add component BannerTeamMemberApprove to allow approving team members
  src/components/__tests__/BannerTeamMemberApprove.cy.js
  src/components/enums/TeamMember.ts
  src/components/global/BannerTeamMemberApprove.vue
  src/components/profile/ProfileDetails.vue
  src/components/types/Results.ts
  src/composables/useApiPutMyTeam.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/pages/IndexPage.vue
  src/pages/ProfilePage.vue
  src/stores/registerChallenge.ts
  src/utils/get_register_challenge_empty_state.ts
  test/cypress/e2e/home.spec.cy.js
  test/cypress/e2e/profile.spec.cy.js
  test/cypress/fixtures/apiGetMyTeamResponseApproved.json
  test/cypress/fixtures/apiGetMyTeamResponseFullTeam.json
  test/cypress/fixtures/apiGetMyTeamResponseOneMember.json
  test/cypress/fixtures/apiGetMyTeamResponseUndecided.json
  test/cypress/fixtures/apiPutMyTeamRequestApproveAllRejectRest.json
  test/cypress/fixtures/apiPutMyTeamRequestApproveFirst.json
  test/cypress/support/commands.js
  test/cypress/utils/index.ts
Labels: enhancement

#926 test/cypress/support: fix 400 response code when testing external links (Twitter)
  test/cypress/support/commonTests.ts
Labels: bug
