Repository auto-mat/ride-to-work-by-bike-frontend, pull requests merged in 2025-06, with the labels that each got.

#1013 src/adapters: fix trips REST API URL endpoint payload distanceMeters field int value type
  src/adapters/tripsAdapter.ts
Labels: bug

#1014 src/stores/results: add new tab teamRegularityCity to results page
  src/components/__tests__/ResultsTabs.cy.js
  src/components/enums/Results.ts
  src/i18n/cs.toml
  src/i18n/en.toml
  src/i18n/sk.toml
  src/stores/results.ts
  test/cypress/fixtures/apiGetResultsResponses.json
  test/cypress/support/commands.js
Labels: enhancement

#1015 src/pages/IndexPage: hide banner Routes
  src/pages/IndexPage.vue
  test/cypress/e2e/home.spec.cy.js
Labels: bug

#1010 test/cypress/e2e: fix routes test by setting exact destination path
  test/cypress/e2e/routes.spec.cy.js
Labels: bug, e2e tests

#1011 src/pages: replace $tc function with $t in RoutesPage
  src/pages/RoutesPage.vue
Labels: enhancement

#1019 test/cypress/e2e: limit cypress-specific code with timeout in StravaApp to component tests
  test/cypress/e2e/strava.spec.cy.js
Labels: bug, e2e tests

#1017 src/stores/challenge: update checking for phase range with Quasar utils
  src/stores/challenge.ts
  test/cypress/e2e/router_rules.cy.js
  test/cypress/fixtures/appAccessTestData.json
  test/cypress/fixtures/loginTokensTestData.json
  test/cypress/support/commonTests.ts
Labels: bug
